# Execution state.
#
# One Firestore database holding the orchestrator's per-execution records. Separate from
# the approvals database in modules/approval, and deliberately so: they have different
# retention needs, different readers, and different consequences when lost. Execution
# state is operational; an approval record is the evidence of who authorized what.
#
# GCP allows multiple named Firestore databases per project, which is what makes that
# separation cheap here. On AWS it is two DynamoDB tables; on Azure a Storage Table and a
# Cosmos container.

terraform {
  required_version = ">= 1.6"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
  }
}

resource "google_firestore_database" "state" {
  project = var.project_id

  # Database IDs are 4-63 characters, lowercase letters, digits and hyphens, and must not
  # look like a UUID. They are also immutable: renaming means creating a new database and
  # losing everything in the old one.
  name        = "${var.name_prefix}-state"
  location_id = var.location

  type = "FIRESTORE_NATIVE"

  # Optimistic concurrency. The orchestrator writes one document per execution and does
  # not contend with itself, so the pessimistic mode buys nothing and costs latency.
  concurrency_mode = "OPTIMISTIC"

  # PITR is a prod concern. It retains a rolling window of versions and costs storage for
  # them; in dev, execution state that is lost is state that can be regenerated by running
  # the thing again.
  point_in_time_recovery_enablement = var.enable_point_in_time_recovery ? "POINT_IN_TIME_RECOVERY_ENABLED" : "POINT_IN_TIME_RECOVERY_DISABLED"

  # With delete protection on, `terraform destroy` fails rather than silently discarding
  # the database. Prod turns this on. It is the reason a prod teardown takes two steps,
  # which is the intended amount of friction.
  delete_protection_state = var.enable_delete_protection ? "DELETE_PROTECTION_ENABLED" : "DELETE_PROTECTION_DISABLED"

  # Distinct from delete_protection_state, and easy to confuse with it. This one governs
  # what Terraform does; that one governs what the API permits.
  deletion_policy = var.enable_delete_protection ? "ABANDON" : "DELETE"
}

# Executions are queried by status and start time — "what is still running", "what failed
# in the last hour". Firestore requires a composite index for any query combining an
# equality filter with an ordering on a different field, and the failure mode is a runtime
# error carrying a console link rather than anything Terraform catches.
resource "google_firestore_index" "executions_by_status" {
  project    = var.project_id
  database   = google_firestore_database.state.name
  collection = var.executions_collection

  fields {
    field_path = "status"
    order      = "ASCENDING"
  }

  fields {
    field_path = "started_at"
    order      = "DESCENDING"
  }
}

# Read access for the orchestrator and anything reconstructing execution history.
resource "google_project_iam_member" "state_user" {
  for_each = var.datastore_user_members

  project = var.project_id
  role    = "roles/datastore.user"
  member  = each.value

  # roles/datastore.user is project-wide: it covers every Firestore database in the
  # project, including the approvals database. Firestore has no per-database IAM role, so
  # this grant is broader than it reads. The narrowing that does exist is at the document
  # level, in security rules, which are not managed here.
  #
  # This is a real divergence from AWS, where a DynamoDB policy names one table ARN. It is
  # recorded in ARCHITECTURE.md rather than papered over.
}
